# Generated by Django 3.2.9 on 2021-11-20 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='breking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='slider',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='videolink',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
