# Generated by Django 3.2.9 on 2021-11-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Category',
        ),
    ]
