# Generated by Django 3.2.9 on 2021-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_genre_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.ManyToManyField(related_name='category', to='news.Category')),
            ],
            options={
                'verbose_name': 'NewsModel',
                'verbose_name_plural': 'NewsModels',
            },
        ),
    ]
